<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Cheryl Isabella" />


<title>Apple Stock Valuation</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Apple Stock Valuation</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="ASV.html">ASV</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore"><strong>Apple Stock Valuation</strong></h1>
<h4 class="author">Cheryl Isabella</h4>

</div>


<p><strong>Assumptions: </strong></p>
<ul>
<li>Assume Apple uses a cost of equity, i.e. 𝑟𝑒 , of 5.50 percent and an
after-tax weighted average cost of capital of 9.50 percent,
i.e. 𝑟𝑤𝑎𝑐𝑐.</li>
<li>The expected return on new investments is 4.00 percent.</li>
</ul>
<div id="data" class="section level2">
<h2>Data</h2>
<pre class="r"><code># income statement
income &lt;- data.frame(cbind(year, total_revenue, EBIT, pretax_income, tax_provision))
income</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["year"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["total_revenue"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["EBIT"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["pretax_income"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["tax_provision"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"2020","2":"2.74515e+11","3":"6.9964e+10","4":"6.7091e+10","5":"9.6800e+09"},{"1":"2019","2":"2.60174e+11","3":"6.9313e+10","4":"6.5737e+10","5":"1.0481e+10"},{"1":"2018","2":"2.65595e+11","3":"7.6143e+10","4":"7.2903e+10","5":"1.3372e+10"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code># balance sheet 
balance &lt;- mutate(balance1, NWC = current_assets - current_liabilities)
balance</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["year"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["PPE"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["current_assets"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["current_liabilities"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["total_debt"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["cash"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["NWC"],"name":[7],"type":["dbl"],"align":["right"]}],"data":[{"1":"2020","2":"3.6766e+10","3":"1.43713e+11","4":"1.05392e+11","5":"1.12436e+11","6":"3.8016e+10","7":"3.8321e+10"},{"1":"2019","2":"3.7378e+10","3":"1.62819e+11","4":"1.05718e+11","5":"1.08047e+11","6":"4.8844e+10","7":"5.7101e+10"},{"1":"2018","2":"4.1304e+10","3":"1.31339e+11","4":"1.16866e+11","5":"1.14483e+11","6":"2.5913e+10","7":"1.4473e+10"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code># cash flow statement 
cashflow &lt;- as.data.frame(cbind(year, depreciation))
cashflow</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["year"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["depreciation"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"2020","2":"1.1056e+10"},{"1":"2019","2":"1.2547e+10"},{"1":"2018","2":"1.0903e+10"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p><br></p>
</div>
<div id="divident-discount-model" class="section level2">
<h2>Divident-Discount Model</h2>
<div id="a-timeline" class="section level3">
<h3>a) Timeline</h3>
<p><img src="timeline_5b.png" /></p>
</div>
<div id="b-dividend-forcast" class="section level3">
<h3>b) Dividend Forcast</h3>
<pre class="r"><code>year_ddm &lt;- c(0, 1, 2, 3, 4, 5)
div_fc &lt;- c(Div, Div*(1+g), Div*(1+g)^2, Div*(1+g)^3, Div*(1+g)^4, Div*(1+g)^5)
div_forecast &lt;- as.data.frame(cbind(year = year_ddm, div_fc))
div_forecast</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["year"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["div_fc"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"0","2":"0.880000"},{"1":"1","2":"1.029160"},{"1":"2","2":"1.203603"},{"1":"3","2":"1.407613"},{"1":"4","2":"1.646204"},{"1":"5","2":"1.925235"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="c-long-term-growth-rate" class="section level3">
<h3>c) Long-term Growth Rate</h3>
<p><span class="math display">\[g = (1-PayoutRatio) *
ReturnOnNewInvestment\]</span></p>
<pre class="r"><code>new_g &lt;- (1-payout) * exp_ret
new_g</code></pre>
<pre><code>## [1] 0.032664</code></pre>
</div>
<div id="d-stock-price-year-five" class="section level3">
<h3>d) Stock Price Year Five</h3>
<p><span class="math display">\[P_5 = \frac{Div_6}{r_e-g} \]</span></p>
<pre class="r"><code>r &lt;- 0.055
Div6 &lt;- div_forecast[6,2] * (1 + new_g)

P5 &lt;-  Div6 / (r-new_g)
round(P5, 2)</code></pre>
<pre><code>## [1] 89.01</code></pre>
</div>
<div id="e-current-stock-price" class="section level3">
<h3>e) Current Stock Price</h3>
<p><span class="math display">\[P_0 = \frac{Div_1}{1+r_e} +
\frac{Div_2}{(1+r_e)^2} + \frac{Div_3}{(1+r_e)^3} +
\frac{Div_4}{(1+r_e)^4} + \frac{Div_5}{(1+r_e)^5} +
\frac{P_5}{(1+r_e)^5} \]</span></p>
<pre class="r"><code>P0_DDM &lt;- (div_forecast[2,2] / 1+r) + (div_forecast[3,2] / (1+r)^2) + (div_forecast[4,2] / (1+r)^3) + (div_forecast[5,2] / (1+r)^4) + (div_forecast[6,2] / (1+r)^5) + (P5 / (1+r)^5)
round(P0_DDM, 2)</code></pre>
<pre><code>## [1] 74.27</code></pre>
<p><br></p>
</div>
</div>
<div id="discounted-free-cash-flow-model" class="section level2">
<h2>Discounted Free Cash Flow Model</h2>
<div id="a-ratios" class="section level3">
<h3>a) Ratios</h3>
<ul>
<li>The average for years 2018, 2019 and 2020 are used.</li>
</ul>
<pre class="r"><code>ratios &lt;- income %&gt;%
  mutate(EBIT_margin = EBIT / total_revenue,
       tax_rate = tax_provision / pretax_income,
       PPE_Sales = balance$PPE / total_revenue,
       deprec_PPE =  cashflow$depreciation / balance$PPE,
       wc_sales = balance$NWC / total_revenue) %&gt;%
  summarise(avg_EBIT_margin = mean(EBIT_margin), 
            avg_tax_rate = mean(tax_rate),
            avg_PPE_Sales = mean(PPE_Sales),
            avg_deprec_PPE = mean(deprec_PPE),
            avg_wc_sales = mean(wc_sales))
ratios</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["avg_EBIT_margin"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["avg_tax_rate"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["avg_PPE_Sales"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["avg_deprec_PPE"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["avg_wc_sales"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"0.2693209","2":"0.1623806","3":"0.1443704","4":"0.3001203","5":"0.1378535"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="b-timeline" class="section level3">
<h3>b) Timeline</h3>
<p><img src="timeline_6b.png" /></p>
</div>
<div id="c-revenue-forcast" class="section level3">
<h3>c) Revenue Forcast</h3>
<pre class="r"><code>#revenues of 2020
revenue2020 &lt;- as.numeric(income %&gt;% filter(year == &quot;2020&quot;) %&gt;% select(total_revenue))
revenue_y5 &lt;- revenue2020*(1+g)^5

year_dfc &lt;- c(0, 1, 2, 3, 4, 5, 6, 7)
growth_factor &lt;- c(1, (1+g), (1+g), (1+g), (1+g), (1+g), (1+new_g), (1+new_g))
revenue_fc &lt;- c(revenue2020, revenue2020*(1+g), revenue2020*(1+g)^2, revenue2020*(1+g)^3, revenue2020*(1+g)^4, revenue_y5, revenue_y5*(1+new_g), revenue_y5*(1+new_g)^2)

forecast_rev &lt;- as.data.frame(cbind(year = year_dfc, growth_factor, revenue_fc))
forecast_rev</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["year"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["growth_factor"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["revenue_fc"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"0","2":"1.000000","3":"274515000000"},{"1":"1","2":"1.169500","3":"321045292500"},{"1":"2","2":"1.169500","3":"375462469579"},{"1":"3","2":"1.169500","3":"439103358172"},{"1":"4","2":"1.169500","3":"513531377383"},{"1":"5","2":"1.169500","3":"600574945849"},{"1":"6","2":"1.032664","3":"620192125880"},{"1":"7","2":"1.032664","3":"640450081480"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="d-ebit-ppe-depreciation-nwc-forecast" class="section level3">
<h3>d) EBIT, PPE, Depreciation &amp; NWC Forecast</h3>
<pre class="r"><code>forecast_dcf &lt;- mutate(forecast_rev, EBIT_fc = ratios$avg_EBIT_margin * revenue_fc,
       PPE_fc = ratios$avg_PPE_Sales * revenue_fc,
       NWC_fc = ratios$avg_wc_sales * revenue_fc,
       depreciation_fc = ratios$avg_deprec_PPE * PPE_fc)
forecast_dcf</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["year"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["growth_factor"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["revenue_fc"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["EBIT_fc"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["PPE_fc"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["NWC_fc"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["depreciation_fc"],"name":[7],"type":["dbl"],"align":["right"]}],"data":[{"1":"0","2":"1.000000","3":"274515000000","4":"73932616204","5":"39631832996","6":"37842842760","7":"11894318239"},{"1":"1","2":"1.169500","3":"321045292500","4":"86464194650","5":"46349428689","6":"44257204608","7":"13910405181"},{"1":"2","2":"1.169500","3":"375462469579","4":"101119875644","5":"54205656851","6":"51758800789","7":"16268218859"},{"1":"3","2":"1.169500","3":"439103358172","4":"118259694565","5":"63393515688","6":"60531917523","7":"19025681955"},{"1":"4","2":"1.169500","3":"513531377383","4":"138304712794","5":"74138716597","6":"70792077543","7":"22250535047"},{"1":"5","2":"1.169500","3":"600574945849","4":"161747361613","5":"86705229060","6":"82791334687","7":"26022000737"},{"1":"6","2":"1.032664","3":"620192125880","4":"167030677432","5":"89537368662","6":"85495630843","7":"26871983369"},{"1":"7","2":"1.032664","3":"640450081480","4":"172486567480","5":"92462017272","6":"88288260129","7":"27749729834"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="e-free-cash-flow-forecast" class="section level3">
<h3>e) Free Cash Flow Forecast</h3>
<p><span class="math display">\[FCF_t = EBIT * (1-𝜏_c) + Depreciation -
CAPEX - (NWC_t - NWC_{t-1}) \]</span></p>
<pre class="r"><code>FCF_forecast &lt;- mutate(forecast_dcf, CAPEX = PPE_fc - lag(PPE_fc),
         NWC_change = NWC_fc - lag(NWC_fc),
         FCF = EBIT_fc * (1- ratios$avg_tax_rate) + depreciation_fc - CAPEX - NWC_change)
FCF_forecast[-1,c(1,10)]</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["year"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["FCF"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"73202533838","_rn_":"2"},{"1":"2","2":"85610363324","_rn_":"3"},{"1":"3","2":"100121319907","_rn_":"4"},{"1":"4","2":"117091883632","_rn_":"5"},{"1":"5","2":"136938957907","_rn_":"6"},{"1":"6","2":"161243682175","_rn_":"7"},{"1":"7","2":"166510545810","_rn_":"8"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="f-horizon-enterprise-value-year-seven" class="section level3">
<h3>f) Horizon Enterprise Value Year Seven</h3>
<p><span class="math display">\[V_7 = \frac{FCF_8}{r_{wacc}-g} =
\frac{FCF_7*(1+g)}{r_{wacc}-g}\]</span></p>
<pre class="r"><code>r_wacc &lt;- 0.095
FCF7 &lt;- as.numeric(filter(FCF_forecast, year == &quot;7&quot;) %&gt;% select(FCF))

V7 &lt;- (FCF7 * (1 + new_g)) / (r_wacc - new_g)
V7</code></pre>
<pre><code>## [1] 2.758429e+12</code></pre>
</div>
<div id="g-enterprise-value" class="section level3">
<h3>g) Enterprise Value</h3>
<p><span class="math display">\[V_0 = \frac{FCF_1}{1+r_{wacc}} +
\frac{FCF_2}{(1+r_{wacc})^2} + \frac{FCF_3}{(1+r_{wacc})^3} +
\frac{FCF_4}{(1+r_{wacc})^4} + \frac{FCF_5}{(1+r_{wacc})^5} +
\frac{FCF_6}{(1+r_{wacc})^6} +
\frac{FCF_7+V_7}{(1+r_{wacc})^7}\]</span></p>
<pre class="r"><code>V0 &lt;- FCF_forecast[2,10]/(1+r_wacc) + FCF_forecast[3,10]/(1+r_wacc)^2 + FCF_forecast[4,10]/(1+r_wacc)^3 + FCF_forecast[5,10]/(1+r_wacc)^4 + FCF_forecast[6,10]/(1+r_wacc)^5 + FCF_forecast[7,10]/(1+r_wacc)^6 + (FCF_forecast[8,10] + V7)/(1+r_wacc)^7
V0</code></pre>
<pre><code>## [1] 2.026078e+12</code></pre>
</div>
<div id="h-current-stock-price" class="section level3">
<h3>h) Current Stock Price</h3>
<p><span class="math display">\[P_0 = \frac{EnterpriseValue_0 + Cash_0 -
Debt_0}{Shares Outstanding}\]</span></p>
<pre class="r"><code>cash2020 &lt;- balance[1,6]
debt2020 &lt;- balance[1,5]

P0_DCF &lt;- (V0 + cash2020 - debt2020) / shares
round(P0_DCF, 2)</code></pre>
<pre><code>## [1] 116.24</code></pre>
<p><br></p>
</div>
</div>
<div id="interpretation-of-the-results" class="section level2">
<h2>Interpretation of the Results</h2>
<ul>
<li>Stock price calculated by dividend discount model: $74.27</li>
<li>Stock price calculated by discounted free cash flow model:
$116.24</li>
<li>The current stock price: $131.46</li>
</ul>
<p>The results show that the stock price calculated using the dividend
discount model and discounted free cash flow model is lower than the
current stock price. This implies that the Apple stock is overvalued
(current price &gt; calculated prices). Therefore, the current stock
price is not justified by the prospected dividends and free cash flows.
In addition, it is more likely that there will be a correction of the
stock. Based on our calculations, it is recommended that investors
should sell the Apple stock. <br></p>
</div>
<div id="differences-in-stock-prices-and-assumptions"
class="section level2">
<h2>Differences in Stock Prices and Assumptions</h2>
<p>The DDM model is based on the forecast of future dividends payments
to the shareholders. Unfortunately, these forecasts are based on
assumptions and have great uncertainty. Firstly, the model is very
sensitive to the dividend growth rate, which is assumed to stay
constant. Secondly, forecasting the future dividends also means
forecasting future earnings, dividend payout rate and future share
count. Thirdly, the earnings depend on the interest expenses, the payout
rate, on whether the firm repurchases shares or not. Lastly, many of
these are decisions made by the management team which are challenging to
forecast. It is also assumed that the return on new investment does not
change in time.</p>
<p>The DCF model focuses on the total value of the firm to equity and
debt holders by calculating the present value of the prospected free
cash flow. The advantage of the DFC is that we do not need to forecast
dividends, share repurchases, or the use of debt to calculate the value
of a firm. Unfortunately, in the DCF model, the free cash flow forecast
also depends greatly on the growth rate. It is assumed that the growth
rate stays constant for the first five years and then change to a
constant long-term growth rate for the following years. Note that the
free cash flow will be paid to debt and equity holders, so the weighted
average cost of capital has to be used.</p>
<p>As aforementioned, the price returned by my models is significantly
lower than the actual stock price. This is because the models only
include a certain number of factors. Investors are also able to evaluate
a stock by non-financial measures. Such can be the reputation of a firm,
the quality of their management team, prospected R&amp;D successes and
much more. Many positive factors can raise the stock price and hence
differ from the model calculations. Especially Apple is has a decent
reputation and is known for its successes in the past. Hence, many
investors are still willing to buy an overvalued stock at a premium.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
